/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBootstrapRouteImport } from './routes/api/bootstrap'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiChatAbortRouteImport } from './routes/api/chat/abort'
import { Route as ApiChatArtifactsRouteImport } from './routes/api/chat/artifacts'
import { Route as ApiChatCommandRouteImport } from './routes/api/chat/command'
import { Route as ApiChatCommandsRouteImport } from './routes/api/chat/commands'
import { Route as ApiChatEventsRouteImport } from './routes/api/chat/events'
import { Route as ApiChatModelRouteImport } from './routes/api/chat/model'
import { Route as ApiChatModelsRouteImport } from './routes/api/chat/models'
import { Route as ApiChatNewRouteImport } from './routes/api/chat/new'
import { Route as ApiChatProvidersRouteImport } from './routes/api/chat/providers'
import { Route as ApiChatQuestionRouteImport } from './routes/api/chat/question'
import { Route as ApiChatResourcesRouteImport } from './routes/api/chat/resources'
import { Route as ApiChatResumeRouteImport } from './routes/api/chat/resume'
import { Route as ApiChatSessionRouteImport } from './routes/api/chat/session'
import { Route as ApiChatSessionsRouteImport } from './routes/api/chat/sessions'
import { Route as ApiChatSettingsRouteImport } from './routes/api/chat/settings'
import { Route as ApiProjectsBrowseRouteImport } from './routes/api/projects/browse'
import { Route as ApiProjectsForkRouteImport } from './routes/api/projects/fork'
import { Route as ApiWorkspaceBrowseRouteImport } from './routes/api/workspace/browse'
import { Route as ApiWorkspaceFileRouteImport } from './routes/api/workspace/file'
import { Route as ApiWorkspaceRootRouteImport } from './routes/api/workspace/root'
import { Route as ApiWorkspaceTreeRouteImport } from './routes/api/workspace/tree'
import { Route as ApiChatModelsDiscoverRouteImport } from './routes/api/chat/models/discover'
import { Route as ApiChatProvidersOauthRouteImport } from './routes/api/chat/providers/oauth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapRoute = ApiBootstrapRouteImport.update({
  id: '/api/bootstrap',
  path: '/api/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAbortRoute = ApiChatAbortRouteImport.update({
  id: '/abort',
  path: '/abort',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatArtifactsRoute = ApiChatArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatCommandRoute = ApiChatCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatCommandsRoute = ApiChatCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatEventsRoute = ApiChatEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatModelRoute = ApiChatModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatModelsRoute = ApiChatModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatNewRoute = ApiChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatProvidersRoute = ApiChatProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatQuestionRoute = ApiChatQuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatResourcesRoute = ApiChatResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatResumeRoute = ApiChatResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatSessionRoute = ApiChatSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatSessionsRoute = ApiChatSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatSettingsRoute = ApiChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiProjectsBrowseRoute = ApiProjectsBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiProjectsForkRoute = ApiProjectsForkRouteImport.update({
  id: '/fork',
  path: '/fork',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiWorkspaceBrowseRoute = ApiWorkspaceBrowseRouteImport.update({
  id: '/api/workspace/browse',
  path: '/api/workspace/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceFileRoute = ApiWorkspaceFileRouteImport.update({
  id: '/api/workspace/file',
  path: '/api/workspace/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRootRoute = ApiWorkspaceRootRouteImport.update({
  id: '/api/workspace/root',
  path: '/api/workspace/root',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceTreeRoute = ApiWorkspaceTreeRouteImport.update({
  id: '/api/workspace/tree',
  path: '/api/workspace/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatModelsDiscoverRoute = ApiChatModelsDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => ApiChatModelsRoute,
} as any)
const ApiChatProvidersOauthRoute = ApiChatProvidersOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => ApiChatProvidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/chat/abort': typeof ApiChatAbortRoute
  '/api/chat/artifacts': typeof ApiChatArtifactsRoute
  '/api/chat/command': typeof ApiChatCommandRoute
  '/api/chat/commands': typeof ApiChatCommandsRoute
  '/api/chat/events': typeof ApiChatEventsRoute
  '/api/chat/model': typeof ApiChatModelRoute
  '/api/chat/models': typeof ApiChatModelsRouteWithChildren
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/chat/providers': typeof ApiChatProvidersRouteWithChildren
  '/api/chat/question': typeof ApiChatQuestionRoute
  '/api/chat/resources': typeof ApiChatResourcesRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/chat/session': typeof ApiChatSessionRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
  '/api/chat/settings': typeof ApiChatSettingsRoute
  '/api/projects/browse': typeof ApiProjectsBrowseRoute
  '/api/projects/fork': typeof ApiProjectsForkRoute
  '/api/workspace/browse': typeof ApiWorkspaceBrowseRoute
  '/api/workspace/file': typeof ApiWorkspaceFileRoute
  '/api/workspace/root': typeof ApiWorkspaceRootRoute
  '/api/workspace/tree': typeof ApiWorkspaceTreeRoute
  '/api/chat/models/discover': typeof ApiChatModelsDiscoverRoute
  '/api/chat/providers/oauth': typeof ApiChatProvidersOauthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/chat/abort': typeof ApiChatAbortRoute
  '/api/chat/artifacts': typeof ApiChatArtifactsRoute
  '/api/chat/command': typeof ApiChatCommandRoute
  '/api/chat/commands': typeof ApiChatCommandsRoute
  '/api/chat/events': typeof ApiChatEventsRoute
  '/api/chat/model': typeof ApiChatModelRoute
  '/api/chat/models': typeof ApiChatModelsRouteWithChildren
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/chat/providers': typeof ApiChatProvidersRouteWithChildren
  '/api/chat/question': typeof ApiChatQuestionRoute
  '/api/chat/resources': typeof ApiChatResourcesRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/chat/session': typeof ApiChatSessionRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
  '/api/chat/settings': typeof ApiChatSettingsRoute
  '/api/projects/browse': typeof ApiProjectsBrowseRoute
  '/api/projects/fork': typeof ApiProjectsForkRoute
  '/api/workspace/browse': typeof ApiWorkspaceBrowseRoute
  '/api/workspace/file': typeof ApiWorkspaceFileRoute
  '/api/workspace/root': typeof ApiWorkspaceRootRoute
  '/api/workspace/tree': typeof ApiWorkspaceTreeRoute
  '/api/chat/models/discover': typeof ApiChatModelsDiscoverRoute
  '/api/chat/providers/oauth': typeof ApiChatProvidersOauthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/chat/abort': typeof ApiChatAbortRoute
  '/api/chat/artifacts': typeof ApiChatArtifactsRoute
  '/api/chat/command': typeof ApiChatCommandRoute
  '/api/chat/commands': typeof ApiChatCommandsRoute
  '/api/chat/events': typeof ApiChatEventsRoute
  '/api/chat/model': typeof ApiChatModelRoute
  '/api/chat/models': typeof ApiChatModelsRouteWithChildren
  '/api/chat/new': typeof ApiChatNewRoute
  '/api/chat/providers': typeof ApiChatProvidersRouteWithChildren
  '/api/chat/question': typeof ApiChatQuestionRoute
  '/api/chat/resources': typeof ApiChatResourcesRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/chat/session': typeof ApiChatSessionRoute
  '/api/chat/sessions': typeof ApiChatSessionsRoute
  '/api/chat/settings': typeof ApiChatSettingsRoute
  '/api/projects/browse': typeof ApiProjectsBrowseRoute
  '/api/projects/fork': typeof ApiProjectsForkRoute
  '/api/workspace/browse': typeof ApiWorkspaceBrowseRoute
  '/api/workspace/file': typeof ApiWorkspaceFileRoute
  '/api/workspace/root': typeof ApiWorkspaceRootRoute
  '/api/workspace/tree': typeof ApiWorkspaceTreeRoute
  '/api/chat/models/discover': typeof ApiChatModelsDiscoverRoute
  '/api/chat/providers/oauth': typeof ApiChatProvidersOauthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/bootstrap'
    | '/api/chat'
    | '/api/health'
    | '/api/projects'
    | '/api/chat/abort'
    | '/api/chat/artifacts'
    | '/api/chat/command'
    | '/api/chat/commands'
    | '/api/chat/events'
    | '/api/chat/model'
    | '/api/chat/models'
    | '/api/chat/new'
    | '/api/chat/providers'
    | '/api/chat/question'
    | '/api/chat/resources'
    | '/api/chat/resume'
    | '/api/chat/session'
    | '/api/chat/sessions'
    | '/api/chat/settings'
    | '/api/projects/browse'
    | '/api/projects/fork'
    | '/api/workspace/browse'
    | '/api/workspace/file'
    | '/api/workspace/root'
    | '/api/workspace/tree'
    | '/api/chat/models/discover'
    | '/api/chat/providers/oauth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/bootstrap'
    | '/api/chat'
    | '/api/health'
    | '/api/projects'
    | '/api/chat/abort'
    | '/api/chat/artifacts'
    | '/api/chat/command'
    | '/api/chat/commands'
    | '/api/chat/events'
    | '/api/chat/model'
    | '/api/chat/models'
    | '/api/chat/new'
    | '/api/chat/providers'
    | '/api/chat/question'
    | '/api/chat/resources'
    | '/api/chat/resume'
    | '/api/chat/session'
    | '/api/chat/sessions'
    | '/api/chat/settings'
    | '/api/projects/browse'
    | '/api/projects/fork'
    | '/api/workspace/browse'
    | '/api/workspace/file'
    | '/api/workspace/root'
    | '/api/workspace/tree'
    | '/api/chat/models/discover'
    | '/api/chat/providers/oauth'
  id:
    | '__root__'
    | '/'
    | '/api/bootstrap'
    | '/api/chat'
    | '/api/health'
    | '/api/projects'
    | '/api/chat/abort'
    | '/api/chat/artifacts'
    | '/api/chat/command'
    | '/api/chat/commands'
    | '/api/chat/events'
    | '/api/chat/model'
    | '/api/chat/models'
    | '/api/chat/new'
    | '/api/chat/providers'
    | '/api/chat/question'
    | '/api/chat/resources'
    | '/api/chat/resume'
    | '/api/chat/session'
    | '/api/chat/sessions'
    | '/api/chat/settings'
    | '/api/projects/browse'
    | '/api/projects/fork'
    | '/api/workspace/browse'
    | '/api/workspace/file'
    | '/api/workspace/root'
    | '/api/workspace/tree'
    | '/api/chat/models/discover'
    | '/api/chat/providers/oauth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBootstrapRoute: typeof ApiBootstrapRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiWorkspaceBrowseRoute: typeof ApiWorkspaceBrowseRoute
  ApiWorkspaceFileRoute: typeof ApiWorkspaceFileRoute
  ApiWorkspaceRootRoute: typeof ApiWorkspaceRootRoute
  ApiWorkspaceTreeRoute: typeof ApiWorkspaceTreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap': {
      id: '/api/bootstrap'
      path: '/api/bootstrap'
      fullPath: '/api/bootstrap'
      preLoaderRoute: typeof ApiBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/abort': {
      id: '/api/chat/abort'
      path: '/abort'
      fullPath: '/api/chat/abort'
      preLoaderRoute: typeof ApiChatAbortRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/artifacts': {
      id: '/api/chat/artifacts'
      path: '/artifacts'
      fullPath: '/api/chat/artifacts'
      preLoaderRoute: typeof ApiChatArtifactsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/command': {
      id: '/api/chat/command'
      path: '/command'
      fullPath: '/api/chat/command'
      preLoaderRoute: typeof ApiChatCommandRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/commands': {
      id: '/api/chat/commands'
      path: '/commands'
      fullPath: '/api/chat/commands'
      preLoaderRoute: typeof ApiChatCommandsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/events': {
      id: '/api/chat/events'
      path: '/events'
      fullPath: '/api/chat/events'
      preLoaderRoute: typeof ApiChatEventsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/model': {
      id: '/api/chat/model'
      path: '/model'
      fullPath: '/api/chat/model'
      preLoaderRoute: typeof ApiChatModelRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/models': {
      id: '/api/chat/models'
      path: '/models'
      fullPath: '/api/chat/models'
      preLoaderRoute: typeof ApiChatModelsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/new': {
      id: '/api/chat/new'
      path: '/new'
      fullPath: '/api/chat/new'
      preLoaderRoute: typeof ApiChatNewRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/providers': {
      id: '/api/chat/providers'
      path: '/providers'
      fullPath: '/api/chat/providers'
      preLoaderRoute: typeof ApiChatProvidersRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/question': {
      id: '/api/chat/question'
      path: '/question'
      fullPath: '/api/chat/question'
      preLoaderRoute: typeof ApiChatQuestionRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/resources': {
      id: '/api/chat/resources'
      path: '/resources'
      fullPath: '/api/chat/resources'
      preLoaderRoute: typeof ApiChatResourcesRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/resume': {
      id: '/api/chat/resume'
      path: '/resume'
      fullPath: '/api/chat/resume'
      preLoaderRoute: typeof ApiChatResumeRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/session': {
      id: '/api/chat/session'
      path: '/session'
      fullPath: '/api/chat/session'
      preLoaderRoute: typeof ApiChatSessionRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/sessions': {
      id: '/api/chat/sessions'
      path: '/sessions'
      fullPath: '/api/chat/sessions'
      preLoaderRoute: typeof ApiChatSessionsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/settings': {
      id: '/api/chat/settings'
      path: '/settings'
      fullPath: '/api/chat/settings'
      preLoaderRoute: typeof ApiChatSettingsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/projects/browse': {
      id: '/api/projects/browse'
      path: '/browse'
      fullPath: '/api/projects/browse'
      preLoaderRoute: typeof ApiProjectsBrowseRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/projects/fork': {
      id: '/api/projects/fork'
      path: '/fork'
      fullPath: '/api/projects/fork'
      preLoaderRoute: typeof ApiProjectsForkRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/workspace/browse': {
      id: '/api/workspace/browse'
      path: '/api/workspace/browse'
      fullPath: '/api/workspace/browse'
      preLoaderRoute: typeof ApiWorkspaceBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/file': {
      id: '/api/workspace/file'
      path: '/api/workspace/file'
      fullPath: '/api/workspace/file'
      preLoaderRoute: typeof ApiWorkspaceFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/root': {
      id: '/api/workspace/root'
      path: '/api/workspace/root'
      fullPath: '/api/workspace/root'
      preLoaderRoute: typeof ApiWorkspaceRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/tree': {
      id: '/api/workspace/tree'
      path: '/api/workspace/tree'
      fullPath: '/api/workspace/tree'
      preLoaderRoute: typeof ApiWorkspaceTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/models/discover': {
      id: '/api/chat/models/discover'
      path: '/discover'
      fullPath: '/api/chat/models/discover'
      preLoaderRoute: typeof ApiChatModelsDiscoverRouteImport
      parentRoute: typeof ApiChatModelsRoute
    }
    '/api/chat/providers/oauth': {
      id: '/api/chat/providers/oauth'
      path: '/oauth'
      fullPath: '/api/chat/providers/oauth'
      preLoaderRoute: typeof ApiChatProvidersOauthRouteImport
      parentRoute: typeof ApiChatProvidersRoute
    }
  }
}

interface ApiChatModelsRouteChildren {
  ApiChatModelsDiscoverRoute: typeof ApiChatModelsDiscoverRoute
}

const ApiChatModelsRouteChildren: ApiChatModelsRouteChildren = {
  ApiChatModelsDiscoverRoute: ApiChatModelsDiscoverRoute,
}

const ApiChatModelsRouteWithChildren = ApiChatModelsRoute._addFileChildren(
  ApiChatModelsRouteChildren,
)

interface ApiChatProvidersRouteChildren {
  ApiChatProvidersOauthRoute: typeof ApiChatProvidersOauthRoute
}

const ApiChatProvidersRouteChildren: ApiChatProvidersRouteChildren = {
  ApiChatProvidersOauthRoute: ApiChatProvidersOauthRoute,
}

const ApiChatProvidersRouteWithChildren =
  ApiChatProvidersRoute._addFileChildren(ApiChatProvidersRouteChildren)

interface ApiChatRouteChildren {
  ApiChatAbortRoute: typeof ApiChatAbortRoute
  ApiChatArtifactsRoute: typeof ApiChatArtifactsRoute
  ApiChatCommandRoute: typeof ApiChatCommandRoute
  ApiChatCommandsRoute: typeof ApiChatCommandsRoute
  ApiChatEventsRoute: typeof ApiChatEventsRoute
  ApiChatModelRoute: typeof ApiChatModelRoute
  ApiChatModelsRoute: typeof ApiChatModelsRouteWithChildren
  ApiChatNewRoute: typeof ApiChatNewRoute
  ApiChatProvidersRoute: typeof ApiChatProvidersRouteWithChildren
  ApiChatQuestionRoute: typeof ApiChatQuestionRoute
  ApiChatResourcesRoute: typeof ApiChatResourcesRoute
  ApiChatResumeRoute: typeof ApiChatResumeRoute
  ApiChatSessionRoute: typeof ApiChatSessionRoute
  ApiChatSessionsRoute: typeof ApiChatSessionsRoute
  ApiChatSettingsRoute: typeof ApiChatSettingsRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatAbortRoute: ApiChatAbortRoute,
  ApiChatArtifactsRoute: ApiChatArtifactsRoute,
  ApiChatCommandRoute: ApiChatCommandRoute,
  ApiChatCommandsRoute: ApiChatCommandsRoute,
  ApiChatEventsRoute: ApiChatEventsRoute,
  ApiChatModelRoute: ApiChatModelRoute,
  ApiChatModelsRoute: ApiChatModelsRouteWithChildren,
  ApiChatNewRoute: ApiChatNewRoute,
  ApiChatProvidersRoute: ApiChatProvidersRouteWithChildren,
  ApiChatQuestionRoute: ApiChatQuestionRoute,
  ApiChatResourcesRoute: ApiChatResourcesRoute,
  ApiChatResumeRoute: ApiChatResumeRoute,
  ApiChatSessionRoute: ApiChatSessionRoute,
  ApiChatSessionsRoute: ApiChatSessionsRoute,
  ApiChatSettingsRoute: ApiChatSettingsRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

interface ApiProjectsRouteChildren {
  ApiProjectsBrowseRoute: typeof ApiProjectsBrowseRoute
  ApiProjectsForkRoute: typeof ApiProjectsForkRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsBrowseRoute: ApiProjectsBrowseRoute,
  ApiProjectsForkRoute: ApiProjectsForkRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBootstrapRoute: ApiBootstrapRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiWorkspaceBrowseRoute: ApiWorkspaceBrowseRoute,
  ApiWorkspaceFileRoute: ApiWorkspaceFileRoute,
  ApiWorkspaceRootRoute: ApiWorkspaceRootRoute,
  ApiWorkspaceTreeRoute: ApiWorkspaceTreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
